# Generated by Django 3.1.7 on 2021-03-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipepost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepost',
            name='photos',
            field=models.ImageField(blank=True, default='p1.png', null=True, upload_to='images2/%y'),
        ),
    ]
