# Generated by Django 3.1.7 on 2021-03-26 06:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipepost', '0002_auto_20210323_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipepost.recipepost')),
            ],
        ),
    ]
