# Generated by Django 3.1.7 on 2021-03-22 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewpost',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('content_name', models.CharField(max_length=150, null=True)),
                ('content', models.TextField()),
                ('photos', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
