# Generated by Django 3.1.7 on 2021-03-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpost', '0002_reviewcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcomment',
            name='comment',
            field=models.TextField(),
        ),
    ]
